/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type DistanceUnit = "km" | "mi";

export type EnergyUnit = "kcal" | "kj";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type GoalKind = "bulk" | "cut" | "maintain" | "performance" | "recomp";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MassUnit = "kg" | "lb";

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface UserGoals {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  effectiveFrom: Timestamp;
  effectiveTo: Timestamp | null;
  id: string;
  kind: GoalKind;
  note: string | null;
  targetBodyMassKg: Numeric | null;
  targetRateKgPerWeek: Numeric | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface UserPreferences {
  agentConfig: Generated<Json>;
  bodyMassUnit: Generated<MassUnit>;
  createdAt: Generated<Timestamp>;
  distanceUnit: Generated<DistanceUnit>;
  energyUnit: Generated<EnergyUnit>;
  locale: Generated<string>;
  massUnit: Generated<MassUnit>;
  timezone: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
  weekStartsOn: Generated<number>;
}

export interface Users {
  authSubject: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  displayName: string | null;
  email: string;
  id: string;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  userGoals: UserGoals;
  userPreferences: UserPreferences;
  users: Users;
}
